# permissions for end users to edit mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: learning-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: mykind-editor-role
rules:
- apiGroups:
  - mygroup.mydomain.com
  resources:
  - mykinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.mydomain.com
  resources:
  - mykinds/status
  verbs:
  - get
